### ISSUE TITLE
Report where the broken link is

### ISSUE THREAD

**Issue by dalonsoa** [ruzickap/action-my-broken-link-checker#104]
**Is your feature request related to a problem? Please describe**
Not sure if it is in your hands of that of `muffet`, but it will be really useful to report not just what links are broken but also where to find them, so they can be fixed easily. 

**Describe the solution you'd like**
For each broken link found, provide a list of places (within the target URL) where that link is found, if found in more than one place. 

**Describe alternatives you've considered**
Nothing comes to my mind, just manually search my documentation for the broken links. 

**Additional context**
None

**Comment by ruzickap** [comment]
I'm sorry, but this feature request needs to be created in https://github.com/raviqqe/muffet repository.

The GitHub Action is only calling muffet like:

```bash
muffet "${CMD_PARAMS[@]}" "${URL}"
```

The output is not in my hands...

**Comment by dalonsoa** [comment]
Yep, that's absolutely fine. I was expecting as much. Many thanks!
