### ISSUE TITLE
Feature request: `ignorePatterns`

### ISSUE THREAD

**Issue by pdg744** [ruzickap/action-my-broken-link-checker#110]
**Is your feature request related to a problem? Please describe**
When I use this link checker, I get very noisy results for issues I'm already aware of.

**Describe the solution you'd like**
- Add support for `ignorePatterns`, as done [here](https://github.com/marketplace/actions/broken-link-check#how-to-use).

**Describe alternatives you've considered**
We're currently using the action linked above because of this feature.

**Comment by ruzickap** [comment]
Hello.

It seems like you are looking for `--exclude` - which is a muffet parameter.

See the example here:

https://github.com/ruzickap/petr.ruzicka.dev/blob/169ba3f73217a566b4cd5b6d2537e7889b90aaaf/.github/workflows/hugo-build.yml#L33

**Comment by pdg744** [comment]
Oh, great -- I'll take a look and follow up if necessary. Thanks for the quick response!
