### ISSUE TITLE
Proposal: New version for muffet 2.10

### ISSUE THREAD

**Issue by pmwmedia** [ruzickap/action-my-broken-link-checker#132]
**Is your feature request related to a problem? Please describe**
I would like to use the feature of configurable HTTP response status codes (https://github.com/raviqqe/muffet/pull/364) of muffet 2.10.

**Describe the solution you'd like**
Please release the branch renovate/raviqqe-muffet-2.x as new version. It contains already muffet 2.10.1.

**Comment by ruzickap** [comment]
Completed in https://github.com/ruzickap/action-my-broken-link-checker/pull/120

**Comment by pmwmedia** [comment]
Thank you for the quick release :)
