### ISSUE TITLE
Bug: This is a sample issue title

### ISSUE THREAD

**Issue by PeterPetrik** [ruzickap/action-my-broken-link-checker#54]
**Describe the bug**
I cannot use the action based on the quick-start. It references "v1" but that is unavailable. 

I managed to use docker setup with:`ruzickap/action-my-broken-link-checker@v2`

**Comment by ruzickap** [comment]
Thank you...
It seems like I accidentally removed that tag... 
I fixed it: https://github.com/ruzickap/action-my-broken-link-checker/releases/tag/v1

Can you try it again?

**Comment by PeterPetrik** [comment]
thanks, but I assume v2 is recommended, right?

**Comment by ruzickap** [comment]
Definitively.
I'm not going to do any 1.x releases...
